### ISSUE TITLE
video_upload getting 'wrong number of arguments (2 for 1)'

### ISSUE THREAD

**Issue by gigacardoso** [kylejginavan/youtube_it#181]
I'm trying to use this gem to upload videos. 

Using this line from the README, or any other of the video_upload for that matter,

client.video_upload("http://media.railscasts.com/assets/episodes/videos/412-fast-rails-commands.mp4", :title => "test",:description => 'some description', :category => 'People',:keywords => %w[cool blah test])

I'm getting the error:

wrong number of arguments (2 for 1)

and the trace shows that it comes from the Read

youtube_it (2.0.0) lib/youtube_it/chain_io.rb:66:in `read'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/generic_request.rb:202:in`copy_stream'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/generic_request.rb:202:in `send_request_with_body_stream'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http/generic_request.rb:132:in`exec'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1404:in `block in transport_request'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1403:in`catch'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1376:in`request'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:852:in`start'
/home/user/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/net/http.rb:1367:in `request'
faraday (0.8.7) lib/faraday/adapter/net_http.rb:75:in`perform_request'
faraday (0.8.7) lib/faraday/adapter/net_http.rb:38:in `call'
faraday (0.8.7) lib/faraday/response.rb:8:in`call'
youtube_it (2.0.0) lib/youtube_it/middleware/faraday_authheader.rb:6:in `call'

any clue on why this happens?

**Comment by gigacardoso** [comment]
don't know why but version 2.0.0 was being used instead of 2.3.2
