### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by d33pika** [kylejginavan/youtube_it#186]
I get Failed (unable to convert video file) on youtube and 

UploadError: 
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/bundler/gems/youtube_it-cc429ea7127f/lib/youtube_it/middleware/faraday_youtubeit.rb:27:in `on_complete'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/gems/faraday-0.8.4/lib/faraday/response.rb:9:in`block in call'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/gems/faraday-0.8.4/lib/faraday/response.rb:63:in `on_complete'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/gems/faraday-0.8.4/lib/faraday/response.rb:8:in`call'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/bundler/gems/youtube_it-cc429ea7127f/lib/youtube_it/middleware/faraday_authheader.rb:17:in `call'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/bundler/gems/youtube_it-cc429ea7127f/lib/youtube_it/middleware/faraday_oauth2.rb:6:in`call'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/gems/faraday-0.8.4/lib/faraday/connection.rb:226:in `run_request'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/gems/faraday-0.8.4/lib/faraday/connection.rb:99:in`post'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/bundler/gems/youtube_it-cc429ea7127f/lib/youtube_it/request/video_upload.rb:92:in `upload'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p194@viki-youtube/bundler/gems/youtube_it-cc429ea7127f/lib/youtube_it/client.rb:106:in`video_upload'
    from (irb):115
    from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'

When I upload the file directly from the browser on youtube it works. The code that uploads the file has not changed in the past three month and was working previously. Also files that uploaded successfully before are failing.

**Comment by d33pika** [comment]
This is not consistent. Closing it.
