### ISSUE TITLE
Secure Connection Error While adding comment to a video

### ISSUE THREAD

**Issue by kamaroon** [kylejginavan/youtube_it#196]
Hi,

 I am currently trying to add a comment to a video from ruby console.I set the ssl_cert_file from the current environment and trying to adding comment for a video post.

I am getting this error:
AuthenticationError: Unspecified error: secure_connection_required

from C:/Ruby193/lib/ruby/gems/1.9.1/gems/youtube_it-2.2.1/lib/youtube_it/middleware/faraday_youtubeit.rb:25:in `on_complete'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/faraday-0.8.8/lib/faraday/response.rb:9:in`block in call'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/faraday-0.8.8/lib/faraday/response.rb:63:in `on_complete'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/faraday-0.8.8/lib/faraday/response.rb:8:in`call'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/youtube_it-2.2.1/lib/youtube_it/middleware/faraday_authheader.rb:17:in`call'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/youtube_it-2.2.1/lib/youtube_it/middleware/faraday_oauth2.rb:6:in`call'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/faraday-0.8.8/lib/faraday/connection.rb:253:in `run_request'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/faraday-0.8.8/lib/faraday/connection.rb:118:in`post'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/youtube_it-2.2.1/lib/youtube_it/request/video_upload.rb:224:in `add_comment'
from C:/Ruby193/lib/ruby/gems/1.9.1/gems/youtube_it-2.2.1/lib/youtube_it/client.rb:145:in`add_comment'
from (irb):4
from C:/Ruby193/bin/irb:12:in `<main>'

please provide any suggestion and help

**Comment by mahhek** [comment]
Hey, I am also getting same error, any method created yet to "add comment" according to new api chagnes?
@kamaroon 
Have you got any solution of this yet? please let me know, thanks.

**Comment by kamaroon** [comment]
@mahhek  NO we didn't get any help to work out this issue.

**Comment by vhsalazar** [comment]
@mahhek  @kamaroon  "IMPORTANT: YouTube is switching to a new commenting system that may require you to modify API calls related to comments. Please review the upcoming changes to comments for a complete explanation of the changes."

https://developers.google.com/youtube/articles/changes_to_comments

You should look G+ Documentation
