### ISSUE TITLE
Exception: #<RuntimeError: Illegal character '&' in raw string

### ISSUE THREAD

**Issue by donnykurnia** [kylejginavan/youtube_it#23]
I got this exception error in my application:

Exception: #<RuntimeError: Illegal character '&' in raw string "
var yt = yt || {};yt.timing = yt.timing || {};yt.timing.tick = function(label, opt_time) {var timer = yt.timing['timer'] || {};if(opt_time) {timer[label] = opt_time;}else {timer[label] = new Date().getTime();}yt.timing['timer'] = timer;};yt.timing.info = function(label, value) {var info_args = yt.timing['info_args'] || {};info_args[label] = value;yt.timing['info_args'] = info_args;};yt.timing.info('e', '903708,901601,911303');yt.timing.wff = true;yt.timing.info('an', '');yt.timing.tick('start');yt.timing.info('li','0');try {yt.timing['srt'] = window.gtbExternal && window.gtbExternal.pageT() ||window.external && window.external.pageT;} catch(e) {}if (window.chrome && window.chrome.csi) {yt.timing['srt'] = Math.floor(window.chrome.csi().pageT);}if (window.msPerformance && window.msPerformance.timing) {yt.timing['srt'] = window.msPerformance.timing.responseStart - window.msPerformance.timing.navigationStart;}    ">
/home/donny/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/rexml/text.rb:91:in `initialize'
/home/donny/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/rexml/parsers/treeparser.rb:43:in`new'
/home/donny/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/rexml/parsers/treeparser.rb:43:in `parse'
/home/donny/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/rexml/document.rb:227:in`build'
/home/donny/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/rexml/document.rb:43:in `initialize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/bundler/gems/youtube_it-810e661994c8/lib/youtube_it/parser.rb:126:in`new'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/bundler/gems/youtube_it-810e661994c8/lib/youtube_it/parser.rb:126:in `parse_content'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/bundler/gems/youtube_it-810e661994c8/lib/youtube_it/parser.rb:9:in`parse'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/bundler/gems/youtube_it-810e661994c8/lib/youtube_it/client.rb:89:in `video_by'
/home/donny/data/Projects/WGS/vortex/jotky-git/app/models/attached_item.rb:48:in`retrieve_youtube_info'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:415:in `_run_validation_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations/callbacks.rb:67:in`run_validations!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations.rb:179:in `valid?'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/validations.rb:55:in`valid?'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/autosave_association.rb:263:in `association_valid?'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/autosave_association.rb:252:in`validate_collection_association'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/will_paginate-2.3.15/lib/will_paginate/finder.rb:168:in `method_missing'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_collection.rb:430:in`method_missing_without_paginate'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_proxy.rb:216:in `method_missing'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_proxy.rb:216:in`each'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_proxy.rb:216:in `send'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_proxy.rb:216:in`method_missing'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/associations/association_collection.rb:430:in `method_missing_without_paginate'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/will_paginate-2.3.15/lib/will_paginate/finder.rb:168:in`method_missing'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/autosave_association.rb:252:in `validate_collection_association'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/autosave_association.rb:180:in`send'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/autosave_association.rb:180:in `validate_associated_records_for_attached_items'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:468:in`_run_validate_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations.rb:212:in `run_validations!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations/callbacks.rb:67:in`run_validations!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:413:in `_run_validation_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations/callbacks.rb:67:in`run_validations!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activemodel-3.0.3/lib/active_model/validations.rb:179:in `valid?'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/validations.rb:55:in`valid?'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/validations.rb:75:in `perform_validations'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/validations.rb:43:in`save'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:237:in`save'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:289:in `with_transaction_returning_status'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/database_statements.rb:139:in`transaction'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:204:in `transaction_without_trace_ActiveRecord_self_name_transaction'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/method_tracer.rb:319:in`transaction'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/method_tracer.rb:141:in `trace_execution_scoped'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/method_tracer.rb:314:in`transaction'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:287:in `with_transaction_returning_status'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:237:in`save'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:248:in `rollback_active_record_state!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/transactions.rb:236:in`save'
/home/donny/data/Projects/WGS/vortex/jotky-git/app/controllers/jots_controller.rb:92:in `create'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/mime_responds.rb:264:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/mime_responds.rb:264:in `retrieve_response_from_mimes'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/mime_responds.rb:191:in`respond_to'
/home/donny/data/Projects/WGS/vortex/jotky-git/app/controllers/jots_controller.rb:91:in `create'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/implicit_render.rb:4:in`send_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/abstract_controller/base.rb:151:in`process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/rendering.rb:11:in `process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/abstract_controller/callbacks.rb:18:in`process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:450:in `_run__135333363__process_action__524098549__callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:409:in`send'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:409:in `_run_process_action_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:93:in`send'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:93:in `run_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/abstract_controller/callbacks.rb:17:in`process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/notifications.rb:52:in`instrument'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/notifications.rb:52:in`instrument'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/rescue.rb:17:in`process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:34:in `process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:252:in`perform_action_with_newrelic_trace'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/method_tracer.rb:141:in `trace_execution_scoped'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:247:in`perform_action_with_newrelic_trace'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:33:in `process_action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/abstract_controller/base.rb:120:in`process'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/abstract_controller/rendering.rb:40:in `process'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal.rb:138:in`dispatch'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_controller/metal.rb:178:in`action'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:62:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:62:in`dispatch'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:27:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-mount-0.6.13/lib/rack/mount/route_set.rb:148:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-mount-0.6.13/lib/rack/mount/code_generation.rb:93:in `recognize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-mount-0.6.13/lib/rack/mount/code_generation.rb:103:in`optimized_each'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-mount-0.6.13/lib/rack/mount/code_generation.rb:92:in `recognize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-mount-0.6.13/lib/rack/mount/route_set.rb:139:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/routing/route_set.rb:492:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:50:in`call_app!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:32:in `call!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:19:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:50:in `call_app!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:32:in`call!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:19:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:50:in`call_app!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:32:in `call!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:19:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:50:in `call_app!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:32:in`call!'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/strategy.rb:19:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/oa-core-0.1.6/lib/omniauth/builder.rb:30:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/newrelic_rpm-2.13.4/lib/new_relic/rack/developer_mode.rb:20:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/haml-3.0.24/lib/sass/plugin/rack.rb:41:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/warden-1.0.3/lib/warden/manager.rb:35:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/warden-1.0.3/lib/warden/manager.rb:34:in`catch'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/warden-1.0.3/lib/warden/manager.rb:34:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/head.rb:14:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/methodoverride.rb:24:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/flash.rb:182:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/cookies.rb:295:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/query_cache.rb:32:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/query_cache.rb:12:in `cache'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/query_cache.rb:31:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activerecord-3.0.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:353:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/callbacks.rb:46:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/callbacks.rb:415:in `_run_call_callbacks'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/callbacks.rb:44:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/sendfile.rb:107:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/rack/logger.rb:13:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/runtime.rb:17:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/activesupport-3.0.3/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/lock.rb:11:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/lock.rb:11:in`synchronize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/lock.rb:11:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/actionpack-3.0.3/lib/action_dispatch/middleware/static.rb:30:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/application.rb:168:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/application.rb:77:in`send'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/application.rb:77:in `method_missing'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/rack/log_tailer.rb:14:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/chunked.rb:15:in`call'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:67:in `process'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:165:in`process_client'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in `each'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:164:in`process_client'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in `run'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in`initialize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in `new'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:291:in`run'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:274:in `initialize'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:274:in`new'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/mongrel-1.2.0.pre2/lib/mongrel.rb:274:in `run'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/handler/mongrel.rb:38:in`run'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/rack-1.2.1/lib/rack/server.rb:213:in `start'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/commands/server.rb:65:in`start'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/commands.rb:30
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/commands.rb:27:in `tap'
/home/donny/.rvm/gems/ree-1.8.7-2011.03@vortex/gems/railties-3.0.3/lib/rails/commands.rb:27
script/rails:6:in`require'
script/rails:6
...
Illegal character '&' in raw string "
var yt = yt || {};yt.timing = yt.timing || {};yt.timing.tick = function(label, opt_time) {var timer = yt.timing['timer'] || {};if(opt_time) {timer[label] = opt_time;}else {timer[label] = new Date().getTime();}yt.timing['timer'] = timer;};yt.timing.info = function(label, value) {var info_args = yt.timing['info_args'] || {};info_args[label] = value;yt.timing['info_args'] = info_args;};yt.timing.info('e', '903708,901601,911303');yt.timing.wff = true;yt.timing.info('an', '');yt.timing.tick('start');yt.timing.info('li','0');try {yt.timing['srt'] = window.gtbExternal && window.gtbExternal.pageT() ||window.external && window.external.pageT;} catch(e) {}if (window.chrome && window.chrome.csi) {yt.timing['srt'] = Math.floor(window.chrome.csi().pageT);}if (window.msPerformance && window.msPerformance.timing) {yt.timing['srt'] = window.msPerformance.timing.responseStart - window.msPerformance.timing.navigationStart;}    "
Line: 
Position: 
Last 80 unconsumed characters:
</script>      <script>       var yt = yt || {};       yt.preload = {};       yt.

How to solve this bug?

**Comment by donnykurnia** [comment]
Sorry, the mistake is in my code, not in youtube_it gem.
