### ISSUE TITLE
Ruby 1.9 error.

### ISSUE THREAD

**Issue by gregwebs** [kylejginavan/youtube_it#42]
I am actually running this under JRuby, but I think you would get the same result in normal Ruby. It would be good to move this library to Nokogiri. I am lazy and just working around with `jruby --1.8`

```
REXML::ParseException: #<Encoding::CompatibilityError: incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)>
org/jruby/RubyRegexp.java:1414:in `=~'
org/jruby/RubyString.java:1588:in `=~'
/home/gweber/.rvm/rubies/jruby-1.6.4/lib/ruby/1.9/rexml/text.rb:131:in `check'
/home/gweber/.rvm/rubies/jruby-1.6.4/lib/ruby/1.9/rexml/text.rb:119:in `initialize'
/home/gweber/.rvm/rubies/jruby-1.6.4/lib/ruby/1.9/rexml/parsers/treeparser.rb:47:in `parse'
/home/gweber/.rvm/rubies/jruby-1.6.4/lib/ruby/1.9/rexml/document.rb:230:in `build'
/home/gweber/.rvm/rubies/jruby-1.6.4/lib/ruby/1.9/rexml/document.rb:43:in `initialize'
/home/gweber/.rvm/gems/jruby-1.6.4/gems/youtube_it-2.1.1/lib/youtube_it/parser.rb:78:in `parse_content'
/home/gweber/.rvm/gems/jruby-1.6.4/gems/youtube_it-2.1.1/lib/youtube_it/parser.rb:15:in `parse'
/home/gweber/.rvm/gems/jruby-1.6.4/gems/youtube_it-2.1.1/lib/youtube_it/request/video_upload.rb:226:in `playlists'
/home/gweber/.rvm/gems/jruby-1.6.4/gems/youtube_it-2.1.1/lib/youtube_it/client.rb:158:in `playlists'
```

**Comment by gregwebs** [comment]
I take it back - this is was a JRuby bug now fixed in jRuby 1.6.5
