### ISSUE TITLE
NoMethodError: undefined method `elements' for nil:NilClass

### ISSUE THREAD

**Issue by masterkain** [kylejginavan/youtube_it#6]
```
YouTubeIt::Client.new(:dev_key => 'yourkey').videos_by(:video_id =>'W8FgayonSGE')
Submitting request [url=http://gdata.youtube.com/feeds/api/videos/W8FgayonSGE]
```

NoMethodError: undefined method `elements' for nil:NilClass
    from /Users/kain/Sites/test/vendor/rails/activesupport/lib/active_support/whiny_nil.rb:52:in`method_missing'
    from /Users/kain/.gem/ruby/1.8/bundler/gems/youtube_it-e1e504affbc4/lib/youtube_it/parser.rb:182:in `parse_content'
    from /Users/kain/.gem/ruby/1.8/bundler/gems/youtube_it-e1e504affbc4/lib/youtube_it/parser.rb:9:in`parse'
    from /Users/kain/.gem/ruby/1.8/bundler/gems/youtube_it-e1e504affbc4/lib/youtube_it/client.rb:75:in `videos_by'

**Comment by masterkain** [comment]
Got it working using video_by(id), probably intended.
