### ISSUE TITLE
faraday dependency conflict with twitter gem

### ISSUE THREAD

**Issue by hisea** [kylejginavan/youtube_it#87]
twitter gem requires faraday 0.8, where youtube_it requries ~> 0.7.6, is there a particular reason we cannot upgrade to 0.8?

if ok I can create a pull request to update the gem version.

Thanks.

**Comment by hisea** [comment]
I did run test on both 0.8 and 0.7.6 and got same results.

4 errors and 1 failure, the error i think is due to some kind of api rate limit.

Started
....................................................E.....EEE...........F..............................................................
Finished in 102.383440 seconds.

  1) Error:
test_should_list_subscriptions(TestClient):
AuthenticationError: Unspecified error: too_many_recent_calls

```
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_youtubeit.rb:24:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:9:in `block in call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:62:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:8:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_authheader.rb:17:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_oauth2.rb:6:in `call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:210:in `run_request'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:98:in `post'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/request/video_upload.rb:344:in `subscribe_channel'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/client.rb:198:in `subscribe_channel'
test/test_client.rb:374:in `test_should_list_subscriptions'
```

  2) Error:
test_should_return_unique_id_from_playlist(TestClient):
NoMethodError: undefined method `unique_id' for nil:NilClass
    test/test_client.rb:286:in`test_should_return_unique_id_from_playlist'

  3) Error:
test_should_subscribe_to_channel(TestClient):
AuthenticationError: Unspecified error: too_many_recent_calls

```
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_youtubeit.rb:24:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:9:in `block in call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:62:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:8:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_authheader.rb:17:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_oauth2.rb:6:in `call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:210:in `run_request'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:98:in `post'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/request/video_upload.rb:344:in `subscribe_channel'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/client.rb:198:in `subscribe_channel'
test/test_client.rb:359:in `test_should_subscribe_to_channel'
```

  4) Error:
test_should_unsubscribe_to_channel(TestClient):
AuthenticationError: Unspecified error: too_many_recent_calls

```
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_youtubeit.rb:24:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:9:in `block in call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:62:in `on_complete'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/response.rb:8:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_authheader.rb:17:in `call'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/middleware/faraday_oauth2.rb:6:in `call'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:210:in `run_request'
/Users/Yinghai/.rvm/gems/ruby-1.9.2-p290@youtube_it/gems/faraday-0.7.6/lib/faraday/connection.rb:98:in `post'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/request/video_upload.rb:344:in `subscribe_channel'
/Users/Yinghai/jugnoo/github/youtube_it/lib/youtube_it/client.rb:198:in `subscribe_channel'
test/test_client.rb:367:in `test_should_unsubscribe_to_channel'
```

  5) Failure:
test_should_have_related_videos(TestVideo) [test/test_video.rb:20]:
<20> expected but was
<25>.

135 tests, 13547 assertions, 1 failures, 4 errors, 0 skips

Test run options: --seed 2785

**Comment by chebyte** [comment]
tests are returning that cause many people are running these so youtube disable temporaly it, and return it

too_many_recent_calls

now I'm working on fix all test and see that all are passing ok and I going to upgrade the faraday version dont worry

see you

**Comment by hisea** [comment]
thank you so much
